### ISSUE TITLE
关于客户端与服务器端的配置问题。

### ISSUE THREAD

**Issue by iszhangjian** [caiwb/5In1RowService#1]
您好，我下载了您代码的压缩包，用pycharm打开客户端后，提示为：
The directory E:\五子棋2\5In1RowClient-master is registered as a Git root, but no Git repositories were found there.
让我配置仓库，第一次接触联网编程，查询资料后，依然报错，请问这个该如何配置呢？
万分感谢！

**Comment by caiwb** [comment]
git配置不影响使用，可以直接到根目录下运行launcher

**Comment by caiwb** [comment]
您好，抱歉才回复邮件，试着用git拉下来，而不是下载压缩包



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            蔡文博
                            
                            
                                
                                    邮箱：whenbber@gmail.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制
            在2017年11月30日 11:05，iszhangjian 写道： 您好，我下载了您代码的压缩包，用pycharm打开客户端后，提示为：
The directory E:\五子棋2\5In1RowClient-master is registered as a Git root, but no Git repositories were found there.
让我配置仓库，第一次接触联网编程，查询资料后，依然报错，请问这个该如何配置呢？
万分感谢！

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/caiwb/5In1RowService","title":"caiwb/5In1RowService","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/caiwb/5In1RowService"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"关于客户端与服务器端的配置问题。 (#1)"}],"action":{"name":"View Issue","url":"https://github.com/caiwb/5In1RowService/issues/1"}}}
